class PricingData {
  static const Map<String, double> ironingPrices = {
    'T-Shirt': 5,
    'Shirt (Formal)': 7,
    'Jeans': 8,
    'Trousers': 7,
    'Shorts': 6,
    'Saree': 12,
    'Dhoti / Lungi': 10,
    'Kurta / Kurti': 8,
    'Blouse': 7,
    'Skirt': 8,
    'Salwar / Leggings': 8,
    'Dupatta / Stole': 6,
    'Undergarments (pair)': 5,
    'Socks (pair)': 4,
    'Towel': 6,
    'Bedsheet (Single)': 10,
    'Bedsheet (Double)': 15,
    'Pillow Covers (pair)': 6,
    'Curtains (panel)': 15,
    'Napkin / Table Linen': 5,
  };

  static const Map<String, double> laundryPrices = {
    'T-Shirt': 12,
    'Shirt (Formal)': 15,
    'Jeans (heavy wash)': 20,
    'Trousers': 16,
    'Shorts': 12,
    'Saree': 25,
    'Dhoti': 18,
    'Kurta': 16,
    'Kurti': 15,
    'Blouse': 12,
    'Skirt': 16,
    'Salwar / Leggings': 15,
    'Dupatta': 10,
    'Undergarments (pair)': 8,
    'Socks (pair)': 5,
    'Towel': 10,
    'Bedsheet (Single)': 18,
    'Bedsheet (Double)': 28,
    'Pillow Covers (pair)': 10,
    'Curtains (panel)': 30,
    'Napkin / Table Linen': 8,
  };

  static const Map<String, double> swiftPrices = {
    'T-Shirt': 20,
    'Shirt (Formal)': 22,
    'Jeans': 30,
    'Trousers': 25,
    'Shorts': 20,
    'Saree': 40,
    'Dhoti': 30,
    'Kurta': 25,
    'Kurti': 22,
    'Blouse': 20,
    'Skirt': 25,
    'Salwar / Leggings': 22,
    'Dupatta': 18,
    'Undergarments (pair)': 15,
    'Socks (pair)': 10,
    'Towel': 18,
    'Bedsheet (Single)': 28,
    'Bedsheet (Double)': 40,
    'Pillow Covers (pair)': 18,
    'Curtains (panel)': 45,
    'Napkin / Table Linen': 15,
  };
}
